# Generated by Django 5.1.1 on 2024-09-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tra_number", models.CharField(max_length=255, null=True)),
                ("name", models.CharField(max_length=255)),
                ("county", models.CharField(max_length=255, null=True)),
                ("region", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("address", models.CharField(max_length=255, null=True)),
                ("town", models.CharField(max_length=255, null=True)),
                ("service_category", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
